---

- name: test raw module
  hosts: windows
  gather_facts: false
  tags: raw
  tasks:
    - name: run getmac
      raw: getmac
    - name: run ipconfig
      raw: ipconfig

- name: test script module
  hosts: windows
  gather_facts: false
  tags: script
  tasks:
    - name: run test script
      script: files/test_script.ps1
    #- name: run bootstrap script
    #  script: files/bootstrap.ps1

- name: test win_ping module
  hosts: windows
  gather_facts: false
  tags: win_ping
  tasks:
    - name: test win_ping
      action: win_ping
      register: ping_result
    - name: check win_ping result
      assert: { that: "ping_result.ping == 'pong'" }
    - name: test win_ping with data
      win_ping: data=blah
      register: ping_result
    - name: check win_ping result with data
      assert: { that: "ping_result.ping == 'blah'" }

- name: test ping.ps1 module
  hosts: windows
  gather_facts: false
  tags: ping
  tasks:
    - name: test ping.ps1
      action: ping.ps1
    - name: test local ping (should use default ping)
      local_action: ping
    - name: test ping (should use ping.ps1)
      action: ping

- name: test fetch module
  hosts: windows
  gather_facts: false
  tags: fetch
  tasks:
    - name: remove local tmp path
      local_action: file path=fetch_tmp state=absent
    - name: fetch a small file
      fetch: src="C:/Windows/win.ini" dest=fetch_tmp
      register: fetch_small
    - name: check fetch small result
      assert: {that: ["fetch_small.changed"] }
    - name: fetch the same small file
      fetch: src="C:/Windows/win.ini" dest=fetch_tmp
      register: fetch_small_again
    - name: check fetch small result
      assert: {that: ["not fetch_small_again.changed"] }
    - name: fetch a large file
      fetch: src="C:/Windows/explorer.exe" dest=fetch_tmp
      register: fetch_large
    - name: check fetch large result
      assert: {that: ["fetch_large.changed"] }
    - name: fetch a large file again
      fetch: src="C:/Windows/explorer.exe" dest=fetch_tmp
      register: fetch_large_again
    - name: check fetch large result
      assert: {that: ["not fetch_large_again.changed"] }

- name: test stat module
  hosts: windows
  gather_facts: false
  tags: stat
  tasks:
    - name: test stat module on file
      stat: path="C:/Windows/win.ini"
      register: stat_file
    - name: check stat_file result
      assert: { that: ["stat_file.stat.exists", "not stat_file.stat.isdir", "stat_file.stat.size > 0", "stat_file.stat.md5"] }
    - name: test stat module on directory
      stat: path="C:/Windows"
      register: stat_dir
    - name: check stat_dir result
      assert: { that: ["stat_dir.stat.exists", "stat_dir.stat.isdir"]}
    - name: test stat module non-existent path
      stat: path="C:/this_file_should_not_exist.txt"
      register: stat_missing
    - name: check stat_missing result
      assert: { that: ["not stat_missing.stat.exists"] }

- name: test setup module
  hosts: windows_not_yet_implemented
  gather_facts: true
  tags: setup
  tasks:
    - name: no-op
      debug: msg="here"

- name: test template module
  hosts: windows_not_yet_implemented
  gather_facts: false
  tags: template
  tasks:
    - name: upload a templated text file
      template: src=templates/ansible_was_here.txt.j2 dest="C:/ansible_was_here.txt"
